heads:
  enabled: true
  payment: DIAMOND # Primary type of payment
  price: 1 # Cost per player head in primary type of payment
  max: 2 # The max number of different player heads trades per Wandering Trader
  min: 1 # The minimum number of different player heads trades per Wandering Trader
  quantity: 1 # The number of trades per player heads item
  stacksize: 1 # The number of items per trade for player heads
  extraheads: true # load extra player heads from config file
  percentchance: 100 # percent chance that the trade shows up between 1 and 100

miniblocks:
  enabled: true
  requireblock: true # Determines if the trade requires the "source" block as well as money
  payment: DIAMOND # Primary type of payment
  price: 1 # Cost per player head in primary type of payment
  max: 2 # The max number of different miniblock trades per Wandering Trader
  min: 1 # The minimum number of different miniblock trades per Wandering Trader
  quantity: 1 # The number of trades per miniblock item
  stacksize: 1 # The number of items per trade for miniblocks
  percentchance: 100 # percent chance that the trade shows up between 1 and 100

hostileheads:
  enabled: true
  payment: DIAMOND # Primary type of payment
  price: 1 # Cost per hostile mob head in primary type of payment
  max: 2 # The max number of different hostile mob heads trades per Wandering Trader
  min: 1 # The minimum number of different hostile mob heads trades per Wandering Trader
  quantity: 1 # The number of trades per hostile mob heads item
  stacksize: 1 # The number of items per trade for hostile mob heads
  percentchance: 100 # percent chance that the trade shows up between 1 and 100

passiveheads:
  enabled: true
  payment: DIAMOND # Primary type of payment
  price: 1 # Cost per player head in primary type of payment
  max: 2 # The max number of different player heads trades per Wandering Trader
  min: 1 # The minimum number of different player heads trades per Wandering Trader
  quantity: 1 # The number of trades per player heads item
  stacksize: 1 # The number of items per trade for player heads
  percentchance: 100 # percent chance that the trade shows up between 1 and 100

neutralheads:
  enabled: true
  payment: DIAMOND # Primary type of payment
  price: 1 # Cost per player head in primary type of payment
  max: 2 # The max number of different player heads trades per Wandering Trader
  min: 1 # The minimum number of different player heads trades per Wandering Trader
  quantity: 1 # The number of trades per player heads item
  stacksize: 1 # The number of items per trade for player heads
  percentchance: 100 # percent chance that the trade shows up between 1 and 100

combined:
  # 0 - none
  # 1 - all (player heads and mobs heads)
  # 2 - passive, hostile mobs and neutral mobs
  combine: 2
  max: 3
  min: 1
  percentchance: 100
  quantity: 3
