name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
api-version: 1.14

main: ${mainClass}

commands:
   uwtreload:
      description: Allows reload of Useful Wandering Trader config
      usage: /uwtreload

permissions:
  uwtreload:
    description: Allows reload of Useful Wandering Trader config
    default: op
